### ISSUE TITLE
Does this must use PIN

### ISSUE THREAD

**Issue by wayn** [gonzalo123/gam-sms#1]
Does this must use PIN? If my sim card has no pin? Thanks

**Comment by gonzalo123** [comment]
It must work without PIN. But you need to setUp the Pin code to null (or empty string)

$sms->insertPin(null); or $sms->insertPin(”);

Anyway I cannot test it. (I haven't any real modem right now).

**Comment by wayn** [comment]
It works fine with $sms-insertPin(''); But if don't have the permission to read and write /dev/ttyS0 also return the pin incorrect.

**Comment by gonzalo123** [comment]
First of all you must ensure that it works using minicom (linux) or hyperterminal (windows). You must have read/write permission within the post
